spring:
  datasource:
    username: mqq
    password: myCynosdb2020
    url: jdbc:mysql://sh-cynosdbmysql-grp-9fgh7n0e.sql.tencentcdb.com:26675/ccSwitcher?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 106.54.3.202
    port: 6739
    password: swServer2020
  cache:
    cache-names: swCache,swRuleCache
    redis:
      keyPrefix: swServer
      timeToLive: 10S