// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.yuewen.nrzx.switcher.sw;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class CommonInParam {

	@TarsStructProperty(order = 0, isRequire = true)
	public int platform = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public int appId = 0;
	@TarsStructProperty(order = 2, isRequire = true)
	public int areaId = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public String serverIp = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public String version = "";

	public int getPlatform() {
		return platform;
	}

	public void setPlatform(int platform) {
		this.platform = platform;
	}

	public int getAppId() {
		return appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	public int getAreaId() {
		return areaId;
	}

	public void setAreaId(int areaId) {
		this.areaId = areaId;
	}

	public String getServerIp() {
		return serverIp;
	}

	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public CommonInParam() {
	}

	public CommonInParam(int platform, int appId, int areaId, String serverIp, String version) {
		this.platform = platform;
		this.appId = appId;
		this.areaId = areaId;
		this.serverIp = serverIp;
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(platform);
		result = prime * result + TarsUtil.hashCode(appId);
		result = prime * result + TarsUtil.hashCode(areaId);
		result = prime * result + TarsUtil.hashCode(serverIp);
		result = prime * result + TarsUtil.hashCode(version);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof CommonInParam)) {
			return false;
		}
		CommonInParam other = (CommonInParam) obj;
		return (
			TarsUtil.equals(platform, other.platform) &&
			TarsUtil.equals(appId, other.appId) &&
			TarsUtil.equals(areaId, other.areaId) &&
			TarsUtil.equals(serverIp, other.serverIp) &&
			TarsUtil.equals(version, other.version) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(platform, 0);
		_os.write(appId, 1);
		_os.write(areaId, 2);
		_os.write(serverIp, 3);
		_os.write(version, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.platform = _is.read(platform, 0, true);
		this.appId = _is.read(appId, 1, true);
		this.areaId = _is.read(areaId, 2, true);
		this.serverIp = _is.readString(3, true);
		this.version = _is.readString(4, true);
	}

}
